### ISSUE TITLE
Schema over riding {{date}} format

### ISSUE THREAD

**Issue by stoweboyd** [kepano/clipper-templates#1]
I created a Obsidian Web Clipper template and tried to get a {{date:YYYY-MM-DD}} -- `{{date:YYYY-MM-DD}} {{title}} - {{author}}` -- in the title of the file being created. However, it appears that the Schema 1.0.1 overrides that formatting.

What I get is this, where the {{date}} includes {{time}} as well.

![date template override](https://github.com/user-attachments/assets/59b0b5b6-0343-491e-9308-fd6bc4514540)

Looking at the page variables in the extension, I see {{date}} resolves to date + time:

![2024-10-09 ¡schma override variables](https://github.com/user-attachments/assets/4e0bd520-08ec-48f0-bb75-904a7ecd9499)

How to fix this?

**Comment by kepano** [comment]
First this is the wrong repo — you should use the Web Clipper repo. This repo is only for templates. Second `{{date:YYYY-MM-DD}}` is not valid way to define date format, you have to use the date filter, like `{{date|date:"YYYY-MM-DD"}} see [readme](https://github.com/obsidianmd/obsidian-clipper).
